# Change the Prometheus server service type to NodePort and set the NodePort to 30000
server:
  service:
    type: NodePort
    nodePort: 30000

# Enable or disable Node Exporter
nodeExporter:
  enabled: true
  service:
    type: ClusterIP  # Change to NodePort or LoadBalancer if needed

# Enable or disable kube-state-metrics
kubeStateMetrics:
  enabled: true

# Enable or disable Alertmanager
alertmanager:
  enabled: true

# Define custom alert rules
serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/prometheus/alert-rules.yaml

# Custom alert rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Additional server configurations, including custom alert rules
serverFiles:
  alert-rules.yaml: |
    groups:
      - name: example.rules
        rules:
          - alert: HighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (pod) > 0.8
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 2 minutes for pod {{ $labels.pod }}."

# Extra Scrape Configurations (Optional, if you want to add more jobs)
extraScrapeConfigs: |
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
