apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
spec:
  secretName: app-tls
  dnsNames:
    - dotnetapp.southcentralus.cloudapp.azure.com
  issuerRef:
    name: app-tls
    kind: ClusterIssuer