apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-tls
  namespace: web
spec:
  dnsNames:
    - hello-world.southcentralus.cloudapp.azure.com
  commonName: hello-world.southcentralus.cloudapp.azure.com
  secretName: hello-tls
  issuerRef:
    name: hello-tls
    kind: ClusterIssuer