apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - update
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
  - list
