apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hello-tls
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: chadc@linux.com
    privateKeySecretRef:
      name: hello-tls
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                nodeSelector:
                  "kubernetes.io/os": linux