apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: server
spec:
  groups:
  - system:authenticated
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth