apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: client
spec:
  groups:
  - system:authenticated
  request: $(cat server.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth