apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
    release: 4.4.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
      release: 4.4.0
  template:
    metadata:
      labels:
        app: ghost
        release: 4.4.0
    spec:
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-pv-claim
      containers:
        - name: ghost
          image: ghost:4.4.0
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 2368
              protocol: TCP
      restartPolicy: Always