apiVersion: v1
kind: LimitRange
metadata:
  name: limit-limits
spec:
  limits:
  - type: Pod
    max:
      cpu: 500m
      memory: 2Mi
    min: 
      cpu: 10m
      memory: 1Mi
  - type: Container
    max:
      cpu: 500m
      memory: 500Mi
    min:
      cpu: 10m
      memory: 5Mi
    default:
      cpu: 250m
      memory: 200Mi
    defaultRequest:
      cpu: 20m
      memory: 20Mi
  - type: openshift.io/Image
    max:
      storage: 1Gi
  - type: openshift.io/ImageStream
    max:
      openshift.io/image-tags: 10
      openshift.io/images: 20
  - type: PersistentVolumeClaim
    min:
      storage: 2Gi
    max:
      storage: 50Gi
    
