apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  storageClassDevices:
    - storageClassName: kut-local-storage
      volumeMode: Block
      devicePaths:
        - /dev/loop0
      #fstype: ext4
