apiVersion: v1
kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret