apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: web
spec:
  serviceAccountName: view-sa
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Always