apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  namespace: ghost
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi