apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-serviceaccount-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: view-sa
  namespace: web